export const healthinsurances = [
  {
    name: "Health Insurance 1",
    description: "One Health that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    ambulancecovered: false,
    diseases: ["Cancer", "HeartAttack", "Tummer"],
    indexeddiseases: [1, 2, 3],
    policyterms: 10,
  },
  {
    name: "Health Insurance 2",
    description: "One Health that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    ambulancecovered: true,
    diseases: ["Cancer", "HeartAttack", "Tummer"],
    indexeddiseases: [1, 2, 3],
    policyterms: 10,
  },
  {
    name: "Health Insurance 3",
    description: "One Health that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    ambulancecovered: false,
    diseases: ["Cancer", "HeartAttack", "Tummer"],
    indexeddiseases: [1, 2, 3],
    policyterms: 10,
  },
  {
    name: "Health Insurance 4",
    description: "One Health that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    ambulancecovered: false,
    diseases: ["Cancer", "HeartAttack", "Tummer"],
    indexeddiseases: [1, 2, 3],
    policyterms: 10,
  },
  {
    name: "Health Insurance 5",
    description: "One Health that you need for all your needs",
    instalments: 1000,
    premiumamount: 100000,
    ambulancecovered: false,
    diseases: ["Cancer", "HeartAttack", "Tummer"],
    indexeddiseases: [1, 2, 3],
    policyterms: 10,
  },
];
export const lifeinsurances = [
  {
    name: "Life Insurance 1",
    description: "One Life that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    policyterms: 10,
  },
  {
    name: "Life Insurance 2",
    description: "One Life that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    policyterms: 10,
  },
  {
    name: "Life Insurance 3",
    description: "One Life that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    policyterms: 10,
  },
  {
    name: "Life Insurance 4",
    description: "One Life that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    policyterms: 10,
  },
  {
    name: "Life Insurance 5",
    description: "One Life that you need for all your needs",
    instalments: 1000,
    premiumamount: 1000000,
    policyterms: 10,
  },
];
